### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Podcakero** [TripleHelixProgramming/arc-following#1]
- Hi, I'm.the programmer from FRC Team 2890, and like you, I am working to implement BobTrajectory and motion profiling for the 2019 season. I was just wondering what process you went through to obtain your velocity, acceleration, P-gain, I-gain, D-gain, and F-fain values. Did you follow the steps layed out in the CTRE Talon SRX Software Reference Manual, or did you so something different?
Here's the current repo and branch I'm working in: https://github.com/Team2890/MotionProfiling/tree/master-merge

**Comment by notmattlythgoe** [comment]
Check out this Wiki on getting everything set up and running.

https://github.com/Team319/BobTrajectory/wiki/Setup

For Velocity and Acceleration we just chose value that make sense. Just choose something that's smaller than what your robot can physically do. A smaller acceleration value is just going to cause your paths to generate with a smaller ramp up to speed. Same with velocity.

**Comment by Podcakero** [comment]
Wonderful. Thanks
